-- 문제1
SELECT * FROM employees;

--NO.2
DESC EMPLOYEES;

--NO.3
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM employees;

--NO.4
SELECT SALARY ,SALARY + 300
FROM employees;

--NO.5
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT*SALARY, SALARY+(COMMISSION_PCT*SALARY)
FROM employees;

--NO.6
SELECT LAST_NAME AS 이름, SALARY 급여
FROM employees;

--NO.7
SELECT LAST_NAME AS Name, SALARY*12 as "Annual Salary"
FROM employees;

--NO.9
SELECT LAST_NAME || ' ' || JOB_ID AS EMPLOYEES
FROM employees;

--NO.10
SELECT LAST_NAME || ' IS A ' || JOB_ID AS EMPLOYEES
FROM employees;

--NO.11
SELECT LAST_NAME || ': 1 YEAR SALARY = ' || SALARY*12
FROM employees;
--NO.12
SELECT JOB_ID
FROM employees;

  