
-- 6
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE EMPNO = 7698;

-- 7
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE ENAME = 'SMITH';

-- 8
SELECT ENAME, HIREDATE, SAL
FROM EMP
WHERE SAL >=2500 AND SAL < 3500;

-- 9
SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL < 2000 OR SAL > 3000;

-- 10
SELECT ENAME,SAL, HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '81/05/01' AND '81/12/03';

-- 11
SELECT EMPNO, ENAME, sal
FROM EMP
WHERE EMPNO NOT IN (7566, 7782, 7934);

-- 12
SELECT ENAME, SAL, DEPTNO, HIREDATE
FROM emp
WHERE DEPTNO = 30 AND SAL <= 2000 AND HIREDATE < '81/05/01';

-- 13
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE (SAL BETWEEN 2000 AND 5000) AND (DEPTNO = 10 OR  DEPTNO = 30);

-- 14
SELECT ENAME, JOB, sal
FROM EMP
WHERE (JOB = 'SALESMAN' OR JOB = 'MANAGER') AND SAL NOT IN (1600, 2975, 2850);

-- 15
SELECT ENAME, DEPTNO
FROM EMP
WHERE ENAME NOT LIKE '%S%' AND DEPTNO = 20;

-- 16
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%A%E%'; 

-- 17
SELECT ENAME, JOB
FROM EMP
WHERE MGR IS NULL;

-- 18
SELECT ENAME, SAL, comm
FROM EMP
WHERE COMM IS NOT NULL;
