-- Standard Function
-- dual table : 가상 테이블 = 결과 확인용
SELECT 1 FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT 12*55 FROM DUAL;

-- 문자함수
-- CHR( N ) : ASCII 값을 문자로 전환하는 함수
SELECT CHR(65) FROM DUAL;


-- 문자열 합치는 커맨드는 || (자바의 +와 같음)
SELECT '안녕하세요' || '건강하세요' FROM DUAL;
-- LPAD(RPAD): 빈칸을 지정문자로 채운다
SELECT LPAD('BBB', 10) FROM DUAL;
SELECT RPAD('BBB', 10) FROM DUAL;
SELECT LPAD('BBB', 10, '-') FROM DUAL;
SELECT LPAD('BBB', 10, '0') FROM DUAL;

-- INSTR == indexOf('c')
SELECT INSTR('123ABC456ABC','A') FROM DUAL;
SELECT INSTR('123ABC456ABC','A', 6) FROM DUAL;
SELECT INSTR('123ABC456ABCABC','A', 6, 2) FROM DUAL; -- 6번째 이후 첫 번째 A
SELECT INSTR('123ABC456ABCABC','D') FROM DUAL; 

-- REPLACE : 문자열 치환
SELECT REPLACE('AAAAABC', 'A') FROM DUAL; -- A가 빈칸으로 삭제됨
SELECT REPLACE('AAAAABC', 'A', 'a') FROM DUAL; -- A를 a로
SELECT REPLACE('AAAAABC', 'AA', 'a') FROM DUAL; -- AA를 a로

-- TRANSLATE: 문자 치환
SELECT TRANSLATE('AAAAABC', 'A', 'a') FROM DUAL; -- A를 a로
SELECT REPLACE('AAAAABC', 'AA', 'a') FROM DUAL; -- AA의 뒤 A는 무시됨

-- 숫자
-- 올림
SELECT CEIL(13.1) FROM DUAL;

-- 내림
SELECT FLOOR(13.9) FROM DUAL;

-- N제곱 값
SELECT POWER(2, 5) FROM DUAL;

-- 반올림
SELECT ROUND(13.5) FROM DUAL;
SELECT ROUND(13.3) FROM DUAL;

-- 부호
-- SIGN
SELECT SIGN(12) FROM DUAL; -- 양수 1
SELECT SIGN(0) FROM DUAL; -- 0은 0
SELECT SIGN(-6) FROM DUAL; -- 음수 -1

-- 버림
-- TRUNC
SELECT TRUNC(12.524) FROM DUAL;
SELECT TRUNC(12.524, 2) FROM DUAL; -- 소수점 2번째 자리까지 남김
SELECT TRUNC(12.524, -1) FROM DUAL; -- 1의 자리수까지 버림
SELECT TRUNC(-1) FROM DUAL;

-- ASCII
SELECT ASCII('A') FROM DUAL;

-- 변환함수
-- TO_CHAR
-- DATE -> VARCHAR2
SELECT TO_CHAR(SYSDATE) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD-HH-MI-SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD/ HH:MI:SS') FROM DUAL;
SELECT TO_CHAR(TO_DATE(SYSDATE, 'YYYY/MM/DD/ HH:MI:SS'),'YYYY/MM/DD/ HH:MI:SS') FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(10000000000, '$999,999,999,999') FROM DUAL;

-- TO_DATE
-- VARCHAR2 -> DATE
SELECT TO_DATE('20201205') FROM DUAL;

SELECT TO_DATE('20201205', 'YYYYMMDD') FROM DUAL;
SELECT TO_DATE('12052020', 'MMDDYYYY') FROM DUAL;

-- TO_NUMBER    VARCHAR2 -> NUMBER
SELECT TO_NUMBER('123') + 1 FROM DUAL;

-- LAST_DAY
SELECT LAST_DAY('20/11/01') FROM DUAL;

-- SUBSTR       ABCdef      substring(1, 3) = BC
--                          substring(4) = ef
SELECT SUBSTR('ABCDEFG', 3) FROM DUAL; -- CDEFG 출력
SELECT SUBSTR('ABCDEFG', 3, 3) FROM DUAL; -- CDE 출력